### ISSUE TITLE
Broken PDFs

### ISSUE THREAD

**Issue by ystrela** [jonaslejon/malicious-pdf#6]
The generated PDFs have an empty line or comments at the beginning. This leads to errors when opening the pdf files depending on the technology.

For example, if a program looks for %PDF-1. at the beginning of the PDF file, uploading or opening the file will fail.

Best Regards

**Comment by jonaslejon** [comment]
Thanks @ystrela I will look into this

**Comment by jonaslejon** [comment]
Can you try now? The file has been updated.
